"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b764$#(&o4o((cvy!z^nsseq5@erq#e^0%5r5a(%c24*f^*sde'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
# Django AppsL:
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
# Third Party Apps :
	"crispy_forms" ,
	"crispy_bootstrap5",
# # اگر social login یا email confirmation جدی می‌خوای، بهتره sites هم باشه
    "django.contrib.sites",

    # allauth
    "allauth",
    "allauth.account",
    # اگر بعداً گوگل/… خواستی:
    # "allauth.socialaccount",
    # "allauth.socialaccount.providers.google",
	
# Developer Apps:
	'accounts',
	'pages',
]

# Crispy Forms settings:
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


MIDDLEWARE = [
	# middlewareهای پیش‌فرض پروژه
	
	'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
	
	# middleware موردنیاز django-allauth
	"allauth.account.middleware.AccountMiddleware" ,
	
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(BASE_DIR.joinpath('templates'))],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
	            
	            # `allauth` needs this from django
	            'django.template.context_processors.request' ,
	            
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

AUTHENTICATION_BACKENDS = [
   
    # Needed to log in by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
    
]

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "app"),
        "USER": os.getenv("DB_USER", "app"),
        "PASSWORD": os.getenv("DB_PASSWORD", "change-me-in-development"),
        "HOST": os.getenv("DB_HOST", "db"),
        "PORT": os.getenv("DB_PORT", "5432"),
	    
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#acconts config
AUTH_USER_MODEL = 'accounts.CustomUser'

ACCOUNT_LOGIN_METHODS = {"email"}

# AllAuth settings:
ACCOUNT_SESSION_REMEMBER = True #غیر فعال کردن تیک remember me برای کاربر و بطور پیش فرض کاربر را بیاد میاورد
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False # یکبار پسورد وارد کردن
ACCOUNT_USERNAME_REQUIRED = False # برای ساخت حساب کاربری به USERNAMR نیازی نیست
ACCOUNT_AUTHENTICATION_METHOD = 'email' # روش احراز و ورود ثبت نام را با email پیاده‌سازی کن
ACCOUNT_EMAIL_REQUIRED = True # برای ساخت حساب کاربری به email نیاز هست
ACCOUNT_UNIQUE_EMAIL = True # پس باید حتما email یکتا باشد چون  برای ساخت حساب کاربری  email نیاز هست

ACCOUNT_SIGNUP_FIELDS = [
	"email*",
	"username",
    "password1*",
]
#Redirection accounts config:
LOGIN_REDIRECT_URL = "/"

LOGIN_URL = "/accounts/login/"
LOGOUT_REDIRECT_URL = "/"                     # خطای 'none' نباید برگردد
ACCOUNT_LOGOUT_REDIRECT_URL = "/logged-out/"   # بعد از تأیید خروج، برگرد به صفحهٔ پیغام


# EMAIL_BACKEND config:
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "noreply@example.com"

ACCOUNT_EMAIL_VERIFICATION = "none"

SITE_ID = 1

